# Generated by Django 6.0.6 on 2026-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Одиночный выбор'), ('multiple', 'Множественный выбор'), ('scale', 'Шкала (числовое значение)'), ('text', 'Текстовый ввод')], default='single', max_length=20),
        ),
    ]
